mywork/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from someapp import views
from library import views

# library url
urlpatterns = [
    
    
    path('',views.index, name='index'),
    path('admin/', admin.site.urls),
    path('catalog/',views.index, name ='index'),
    path('books/', views.BookListView.as_view() , name = 'books'),
    path('book/<int:pk>',views.BookDetailView.as_view(template_name = 'book_detail.html'),name='book-detail'),
    path('author/',views.AuthorListView.as_view(), name = 'author'),
    path('author/<int:pk>',views.AuthorDetailView.as_view(template_name = 'author_detail.html'), name= 'author-detail'),
    path('mybooks/',views.LoanedBooksByUserListView.as_view(),name='my-borrowed'),

    path('someapp/',views.index1, name="index1"),
    path('someapp/generator/', views.generator, name='generator'),
    path('someapp/password/', views.password, name='password'),
    path('someapp/lottery/', views.lottery, name="lottery"),
    path('someapp/bmi/', views.bmi, name='bmi'),
    path('someapp/gym/', views.gym, name='gym'),
    path('someapp/gym1/', views.gym1, name='gym1'),
    
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    
]

 #someapp url

    


    # path('admin/', admin.site.urls),
    # path('register/', views.register, name='register'),
    # path('todolist/', views.todolist, name = "todolist"),
    # path('', views.user_login, name="login"),
    # path('logout/', views.user_logout, name='logout'),
    # path('view/<int:todo_id>',views.viewtodo,name="viewtodo"),
    # path('create/', views.createtodo, name="createtodo"),
    # path('view/<int:todo_id>/complete', views.completetodo, name="completetodo"),
    # path('view/<int:todo_id>/delete', views.deletetodo, name="deletetodo"),
    # path('complete/', views.completed, name="completed"),

    
    # path('listall/', views.listall, name = "listall"),
    # path('insert/', views.insert),
    # path('modify/', views.modify),
    # path('delete/', views.delete),

library/models.py
from dis import dis
import uuid
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction")
    def __str__(self):
        return self.name

class Language(models.Model):
    la = models.CharField(max_length=100, help_text='Enter the book\'s natural language(e.g. English, French, Japan etc.)')

    def __str__(self):
        return self.la     

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    language = models.ManyToManyField(Language, help_text='Select a language for this book' )
    
    def display_genre(self):
        return ','.join(genre.name for genre in self.genre.all()[:3])
        
    display_genre.short_description = 'Genre'

    def display_language(self):
        return ','.join(language.la for language in self.language.all()[:3])
        
    display_language.short_description = 'Language'

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

class Bookinstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
    help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey(Book,on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',)

    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    

    class Meta:
        ordering = ['due_back']


    def __str__(self):
        return f'{self.id}({self.book.title}),{self.status},{self.due_back}'


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['last_name','first_name']

    def get_absolute_url(self):
        return reverse('author-detail',args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name},{self.first_name}'

library/views.py
from msilib.schema import ListView
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import *
from django.views import generic
from django.contrib import sessions
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.contrib.auth import login, logout , authenticate
from django.contrib.auth.decorators import login_required
import random
# Create your views here.

def index(request):
    num_books = Book.objects.all().count()
    num_instance = Bookinstance.objects.all().count()
    num_instance_available = Bookinstance.objects.filter(status__exact = 'a').count()
    num_author = Author.objects.all().count()
    num_visits = request.session.get('num_visits',0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instance,
        'num_instance_available': num_instance_available,
        'num_authors': num_author,
        'num_visits': num_visits,
    }

    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):
    model = Book
    template_name = 'book_list.html'
    paginate_by =  5
class BookDetailView(generic.DetailView):
    model = Book

    def book_detail_view(request, primary_key):
        book = get_object_or_404(Book, pk=primary_key)

        return render(request, 'book_detail.html', context={'book':book})


class AuthorListView(generic.ListView):
    model = Author
    template_name = 'author_list.html'
    paginate_by =  5

class AuthorDetailView(generic.DetailView):
    model = Author
    

    def author_detail_view(request, primary_key):
        author = get_object_or_404(Author, pk = primary_key)
        
        return render(request, 'author_detail.html', context = {'author':author})

    

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    model = Bookinstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    
    def get_queryset(self):
        return Bookinstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

@login_required
def generator(request):
    return render(request,'generator.html')


@login_required
def password(request):

    if request.GET.get('number-length'):
        length = eval(request.GET.get('number-length'))
    else:
        length = eval(request.GET.get('length'))

    password = ''
    characters = list('abcdefghijklmnopqrstuvwxyz')

    if request.GET.get('uppercase'):
        characters+= list('abcdefghijklmnopqrstuvwxyz'.upper())

    if request.GET.get('number'):
        characters+= list('0123456789')

    if request.GET.get('special'):
        characters+= list('!@#$%^&*()_~')    

    for i in range(length):
        password += random.choice(characters)

    return render(request, 'password.html' , {'password': password})

@login_required
def lottery(request):
    return render(request ,"lottery.html")


@login_required
def bmi(request):
    return render(request ,"bmi.html")


@login_required
def gym(request):
    return render(request ,"gym.html")
    
@login_required
def gym1(request):
    return render(request ,"gym1.html")

@login_required
def index1(request):
    return render(request ,"index1.html")

library/templates/author_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Author:{{ author.first_name }}, {{ author.last_name }}</h1>
<p>{{author.date_of_birth}}-{{author.date_of_death}}</p>

<p><strong>Books</strong></p>
{% for books in author.book_set.all %}
<p><a href="{% url 'book-detail' books.pk %}">{{ books.title }}</a>({{ books.bookinstance_set.all.count }})</p>
<p>{{ books.summary }}</p>

{% endfor %}

{% endblock %}

library/templates/author_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Author List</h1>

<ul>
    {% if author_list %}
    {% for author in author_list %}
    <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }}, {{ author.last_name }}({{ author.date_of_birth }} - {{ author.date_of_death }})</a>
    </li>
    {% endfor %}
    {% endif %}
</ul>


{% endblock %} 

library/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'books' %}">All books</a></li>
        <li><a href="{% url 'author' %}">All authors</a></li>
      </ul>

      {% if user.is_authenticated %}
        <li>User:{{ user.get_username }}</li>
        <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
        
        <li><a href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'login' %}?next={{request.path}}">Login</a></li>
        {% endif %}
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      
      {% block pagination %}
        {% if is_paginated %}
        <div class="pagination">
          <span class="page-links">
            {% if page_obj.has_previous %}
            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="page-current">
              <p>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</p>
            </span>
            {% if page_obj.has_next %}
              <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
          </span>
        </div>
        {% endif %}
      {% endblock %}
      </div>

    </div>
  </div>
</body>
</html>

library/templates/bmi.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-Hant">

<head>
    <meta charset="UTF-8">
    <title>BMI Calculator</title>
    <link rel="stylesheet" href="{% static 'css/web.css' %}">

    <style>
        form {
            text-align: center;
            border-radius: 10px;
            margin: 10px;
        }

        input {
            text-align: center;
        }

        @media screen and (max-width:1920px) {
            form {
                padding: 20px 60px;
            }

            label,
            input,
            button {
                width: 100%;
            }
        }

        @media screen and (max-width:768px) {

            label,
            input,
            button {
                width: 80%;
            }
        }
    </style>
</head>

<body>
    <div id="container">
        <div class="banner">BMI Calculator</div>
        <form action="">
            <label for="name">姓名:</label>
            <input type="text" name="name" id="name">
            <br>
            <label for="height">身高:</label>
            <input type="number" name="height" id="height">
            <br>
            <label for="weight">體重:</label>
            <input type="number" name="weight" id="weight">
            <br>
            <p class="result">BMI:</p>
            <input type="button" id="count" value="計算" onclick="calc()"></button> 
            <!-- onclick用來呼叫函式 -->
        </form>
    </div>
    <script src="{% static 'js/bmi.js' %}"></script>
</body>

</html>

library/templates/book_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Title:{{ book.title }}</h1>

<p><strong>Author:</strong><a href="{% url 'author-detail' book.author.pk %}"> {{ book.author }}</a></p>
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Language:</strong> {% for language in book.language.all %}{{ language }}{% endfor %}</p>
<p><strong>Genre:</strong> {% for genre in book.genre.all %}{{ genre }}{% endfor %}</p>

<div style="margin: left 20px; margin: top 20px;">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger {% else %} text-waring{% endif %}">
        {{ copy.get_status_display }}
    </p>
        {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong>{{ copy.due_back }}</p>
        {% endif %}
        <p><strong>Imprint:</strong>{{ copy.imprint }}</p>
        <p class="text-muted"><strong>Id:</strong>{{ copy.id }}</p>
        {% endfor %}
</div>
{% endblock %}

library/templates/book_list.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <h1>Book List</h1>
    {% if book_list %}
    <ul>
        {% for book in book_list %}
        <li>
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
            ({{ book.author }})
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There  are no books in the library.</p>
    {% endif%}
    {% endblock %}
    
</body>
</html>

library/templates/generator.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello Django 密碼產生器</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
</head>
<body>
   
    <h1>Password Generator</h1>
    <form action="{% url 'password' %}" id="password" method="GET">
       <label for="">密碼長度</label>
        <select name="length" id="">
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8" selected="selected">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
        </select>
        <br>
        <label for="">自訂長度</label>
        <input type="number" name="number-length" id="">
            <input type="checkbox" name="uppercase" id="">大寫
            <input type="checkbox" name="number" id="">數字
            <input type="checkbox" name="special" id="">特殊符號
            <br>
            <input type="submit" value="產生"></button>
    </form>
    <hr>
    <a href="{% url 'login' %}">home</a>
</body>
</html>

library/templates/index.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% block content %}
        <h1>Local Library Home</h1>
        <p>Welcome to LocalLibrary, a website developed by <em>Kilain</em>!</p>

    <h2>Dynamic content</h2>
    <p>The library has the following record counts:</p>
    <ul>
        <li><strong>Books:</strong>&nbsp;{{ num_books }}</li>
        <li><strong>Copies:</strong>&nbsp;{{ num_instances }}</li>
        <li><strong>Copies available:</strong>&nbsp;{{ num_instance_available }}</li>
        <li><strong>Authors:</strong>&nbsp;{{num_authors }}</li>
    </ul>

    <p>You have visited this page {{ num_visits }} {% if num_visits == 1 %}time{% else %}times{% endif %}</p>
    {% endblock  %}
</body>
</html>

library/templates/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/web.css">
    <title>作品預覽</title>
</head>
<h1>My Works</h1>
<body style="text-align:center; font-size:large;">
    <a href="gym">Gym Web</a><br>
    <a href="gym1">Gym Web Test</a><br>
    <a href="bmi">Bmi Calculator</a><br>
    <a href="lottery">Lotto Generator</a><br>
    <a href="generator">password Generator</a><br>


        
</body>
</html>

library/templates/lottery.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/lottery.css' %}">
    <title>Lotto Generator</title>

</head>

<body onload="getTime()">
    <div class="container">
        <div id="banner">
            大樂透Bingo!!
        </div>
        <select name="numner-count" id="count-el">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
        </select>
        <button class="btn-el">開獎!</button>
        <div>
            <h3 class="showtime">Now Time</h3>
            <table border="1" id="table-el">
                <tr>
                    <td>$$</td>
                    <td>$$</td>
                    <td>$$</td>
                    <td>$$</td>
                    <td>$$</td>
                    <td>$$</td>
                    <td>$$</td>
                </tr>
            </table>
        </div>

        <button class="changecolor">Change Color</button>
        <script src="{% static 'js/index.js' %}"></script>
    </div>
    <hr>
    <a href="{% url 'login' %}">home</a>
</body>

</html>